START_COMMAND = "start"
HELP_COMMAND = "help"
SUPPORT_COMMAND = "support"
DELETE_COMMAND = "delete_account"
START_DESCRIPTION = "Запустить бота"
HELP_DESCRIPTION = "Получить помощь"
SUPPORT_DESCRIPTION = "Связаться с поддержкой"
DELETE_DESCRIPTION = "Удалить аккаунт"
