GO_PATTERN = "^go$"
NEXT_TIME_PATTERN = "^next_time$"
ROLE_CHOICE_PATTERN = "^(student|recruiter)$"
RESTART_PATTERN = "^restart$"
TO_SUPPORT_PATTERN = "^support$"
PARTICIPATE_PATTERN = "^participate$"
