GO_PATTERN = "^go$"
NEXT_TIME_PATTERN = "^next_time$"
ROLE_CHOICE_PATTERN = "^(itspecialist|recruiter)$"
RESTART_PATTERN = "^restart$"
TO_SUPPORT_PATTERN = "^support$"
PARTICIPATE_PATTERN = "^participate$"
CONTINUE_NAME_PATTERN = "^continue_name.*"
CHANGE_NAME_PATTERN = "^change_name$"
PROFESSION_CHOICE_PATTERN = "^profession.*$"
PROFILE_PATTERN = "^(all_right|fill_again)*$"
FOUND_PAIR = "^found_pair$"
CALLING_IS_SUCCESSFUL = "^(yes|no)$"
PHONE_NUMBER_PATTERN = (
    r"^(\+?\d\d?\d?\d?)\((\d{3})\)(\d{3})\-(\d{2})\-(\d{2})$"
)
MESSAGE_KEY_PATTERN = r"^[A-z0-9_]+$"
DELETE_PATERN = "^deleting_account$"
