# Generated by Django 4.2.5 on 2023-09-13 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recruiter",
            fields=[
                (
                    "user_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "surname",
                    models.CharField(max_length=255, verbose_name="Фамилия"),
                ),
                (
                    "tg_username",
                    models.CharField(
                        max_length=255, verbose_name="Ник в телеграмме"
                    ),
                ),
                ("registration_date", models.DateField(auto_now_add=True)),
                ("last_login_date", models.DateField(auto_now=True)),
                ("is_vacant", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "surname",
                    models.CharField(max_length=255, verbose_name="Фамилия"),
                ),
                (
                    "tg_username",
                    models.CharField(
                        max_length=255, verbose_name="Ник в телеграмме"
                    ),
                ),
                ("registration_date", models.DateField(auto_now_add=True)),
                ("last_login_date", models.DateField(auto_now=True)),
                ("is_vacant", models.BooleanField(default=False)),
                (
                    "profession",
                    models.CharField(
                        choices=[
                            ("AN", "Аналитик"),
                            ("BA", "Бэкенд-разработчик"),
                            ("FR", "Фронтенд-разработчик"),
                            ("TE", "Тестировщик"),
                        ],
                        default="AN",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PassedPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "is_interview_successful",
                    models.BooleanField(default=False),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.recruiter",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreatedPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.recruiter",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.student",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="passedpair",
            constraint=models.UniqueConstraint(
                fields=("student", "recruiter"), name="unique_passed_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="createdpair",
            constraint=models.UniqueConstraint(
                fields=("student",), name="unique_student"
            ),
        ),
        migrations.AddConstraint(
            model_name="createdpair",
            constraint=models.UniqueConstraint(
                fields=("recruiter",), name="unique_recruiter"
            ),
        ),
        migrations.AddConstraint(
            model_name="createdpair",
            constraint=models.UniqueConstraint(
                fields=("student", "recruiter"), name="unique_created_pair"
            ),
        ),
    ]
