# Generated by Django 4.2.5 on 2023-09-14 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Telegram id')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('tg_username', models.CharField(max_length=255, verbose_name='Ник в телеграмме')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_login_date', models.DateField(auto_now=True, verbose_name='Заходил в последний раз')),
                ('is_vacant', models.BooleanField(default=False, verbose_name='Есть пара')),
            ],
            options={
                'verbose_name': 'Рекрутер',
                'verbose_name_plural': 'Рекрутеры',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Telegram id')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('tg_username', models.CharField(max_length=255, verbose_name='Ник в телеграмме')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_login_date', models.DateField(auto_now=True, verbose_name='Заходил в последний раз')),
                ('is_vacant', models.BooleanField(default=False, verbose_name='Есть пара')),
                ('profession', models.CharField(choices=[('AN', 'Аналитик'), ('BA', 'Бэкенд-разработчик'), ('FR', 'Фронтенд-разработчик'), ('TE', 'Тестировщик')], default='AN', max_length=2, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='PassedPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('is_interview_successful', models.BooleanField(default=False, verbose_name='Встреча прошла успешно')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.recruiter', verbose_name='Рекрутер')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Завершенная пара',
                'verbose_name_plural': 'Завершенные пары',
            },
        ),
        migrations.CreateModel(
            name='CreatedPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.recruiter', verbose_name='Рекрутер')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Текущая пара',
                'verbose_name_plural': 'Текущие пары',
            },
        ),
        migrations.AddConstraint(
            model_name='passedpair',
            constraint=models.UniqueConstraint(fields=('student', 'recruiter'), name='unique_passed_pair'),
        ),
        migrations.AddConstraint(
            model_name='createdpair',
            constraint=models.UniqueConstraint(fields=('student',), name='unique_student'),
        ),
        migrations.AddConstraint(
            model_name='createdpair',
            constraint=models.UniqueConstraint(fields=('recruiter',), name='unique_recruiter'),
        ),
        migrations.AddConstraint(
            model_name='createdpair',
            constraint=models.UniqueConstraint(fields=('student', 'recruiter'), name='unique_created_pair'),
        ),
    ]
