# Generated by Django 4.2.5 on 2023-09-20 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название профессии')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('telegram_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Telegram User ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('telegram_username', models.CharField(max_length=255, unique=True, verbose_name='Ник в телеграмме')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_login_date', models.DateField(auto_now=True, verbose_name='Заходил в последний раз')),
                ('has_pair', models.BooleanField(default=False, verbose_name='Есть пара')),
            ],
            options={
                'verbose_name': 'Рекрутер',
                'verbose_name_plural': 'Рекрутеры',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('telegram_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Telegram User ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('telegram_username', models.CharField(max_length=255, unique=True, verbose_name='Ник в телеграмме')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_login_date', models.DateField(auto_now=True, verbose_name='Заходил в последний раз')),
                ('has_pair', models.BooleanField(default=False, verbose_name='Есть пара')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='bot.profession', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='PassedPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('interview_successful', models.BooleanField(default=False, verbose_name='Встреча прошла успешно')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.recruiter', verbose_name='Рекрутер')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Завершенная пара',
                'verbose_name_plural': 'Завершенные пары',
            },
        ),
        migrations.CreateModel(
            name='CreatedPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.recruiter', verbose_name='Рекрутер')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Активная пара',
                'verbose_name_plural': 'Активные пары',
            },
        ),
        migrations.AddConstraint(
            model_name='passedpair',
            constraint=models.UniqueConstraint(fields=('student', 'recruiter'), name='unique_passed_pair'),
        ),
        migrations.AddConstraint(
            model_name='createdpair',
            constraint=models.UniqueConstraint(fields=('student',), name='unique_student'),
        ),
        migrations.AddConstraint(
            model_name='createdpair',
            constraint=models.UniqueConstraint(fields=('recruiter',), name='unique_recruiter'),
        ),
        migrations.AddConstraint(
            model_name='createdpair',
            constraint=models.UniqueConstraint(fields=('student', 'recruiter'), name='unique_created_pair'),
        ),
    ]
