# Generated by Django 4.2.5 on 2023-09-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='search_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала поиска'),
        ),
        migrations.AddField(
            model_name='itspecialist',
            name='search_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала поиска'),
        ),
    ]
