# Generated by Django 4.2.5 on 2023-09-25 13:42

from django.db import migrations


def create_profession_analyst(apps, schema_editor):
    """Create name of profession 'Analyst'."""
    Profession = apps.get_model("bot", "Profession")
    Profession.objects.create(
        name="Аналитик",
    )


def remove_profession_analyst(apps, schema_editor):
    """Remove profession 'Analyst' instance."""
    Profession = apps.get_model("bot", "Profession")
    remove_profession = Profession.objects.get(name="Аналитик")
    remove_profession.delete()


def create_profession_backend_developer(apps, schema_editor):
    """Create name of profession 'Backend developer'."""
    Profession = apps.get_model("bot", "Profession")
    Profession.objects.create(
        name="Бэкенд-разработчик",
    )


def remove_profession_backend_developer(apps, schema_editor):
    """Remove profession 'Backend developer' instance."""
    Profession = apps.get_model("bot", "Profession")
    remove_profession = Profession.objects.get(name="Бэкенд-разработчик")
    remove_profession.delete()


def create_profession_frontend_developer(apps, schema_editor):
    """Create name of profession 'Frontend developer'."""
    Profession = apps.get_model("bot", "Profession")
    Profession.objects.create(
        name="Фронтенд-разработчик",
    )


def remove_profession_frontend_developer(apps, schema_editor):
    """Remove profession 'Frontend developer' instance."""
    Profession = apps.get_model("bot", "Profession")
    remove_profession = Profession.objects.get(name="Фронтенд-разработчик")
    remove_profession.delete()


def create_profession_tester(apps, schema_editor):
    """Create name of profession 'Tester'."""
    Profession = apps.get_model("bot", "Profession")
    Profession.objects.create(
        name="Тестировщик",
    )


def remove_profession_tester(apps, schema_editor):
    """Remove profession 'Frontend developer' instance."""
    Profession = apps.get_model("bot", "Profession")
    remove_profession = Profession.objects.get(name="Тестировщик")
    remove_profession.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_recruiter_search_start_time_and_more'),
    ]

    operations = [
        migrations.RunPython(
            create_profession_analyst,
            reverse_code=remove_profession_analyst
        ),
        migrations.RunPython(
            create_profession_backend_developer,
            reverse_code=remove_profession_backend_developer
        ),
        migrations.RunPython(
            create_profession_frontend_developer,
            reverse_code=remove_profession_frontend_developer
        ),
        migrations.RunPython(
            create_profession_tester,
            reverse_code=remove_profession_tester
        ),
    ]
