# Generated by Django 4.2.5 on 2023-09-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_add_profession"),
    ]

    operations = [
        migrations.AddField(
            model_name="profession",
            name="professional_key",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
