# Generated by Django 4.2.5 on 2023-10-02 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0004_changed_surname"),
        ("bot", "0004_profession_professional_key"),
    ]

    operations = []
