# Generated by Django 4.2.6 on 2023-10-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0005_merge_20231002_1739"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Название ссылки"
                    ),
                ),
                ("url", models.URLField(verbose_name="Ссылка", null=True)),
                (
                    "url_key",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Ключ ссылки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка на форму",
                "verbose_name_plural": "Ссылки на формы",
            },
        ),
    ]
