# Generated by Django 4.2.6 on 2023-10-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0008_add_profession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profession",
            name="professional_key",
            field=models.CharField(
                blank=True, editable=False, max_length=128, null=True, unique=True
            ),
        ),
    ]
