# Generated by Django 4.2.6 on 2023-11-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0008_add_profession"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Название сообщения бота",
                    ),
                ),
                (
                    "message",
                    models.TextField(unique=True,
                                     verbose_name="Текст сообщения бота"),
                ),
            ],
            options={
                "verbose_name": "Сообщение бота",
                "verbose_name_plural": "Сообщения бота",
            },
        ),
    ]
