# Generated by Django 4.2.6 on 2023-11-13 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0009_messagebot"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagebot",
            name="message_key",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-z0-9_]+$",
                        code="Invalid key",
                        message=(
                            "Ключ должен стостоять только из латинских "
                            "букв, цифр и знака подчеркивания"
                        ),
                    )
                ],
                verbose_name="Ключ сообщения бота",
            ),
            preserve_default=False,
        ),
    ]
