# Generated by Django 4.2.6 on 2023-11-22 14:02

from django.db import migrations


def create_messages(apps, schema_editor):
    """Создание сообщений бота."""
    MessageBot = apps.get_model("bot", "MessageBot")
    messages = (
        MessageBot(title="Поддержка",
                   message=(
                            "Чтобы обратиться в поддержку, "
                            "воспользуйся формой по ссылке ниже."
                    ),
                   message_key="assistance_message"),
        MessageBot(title="Помощь",
                   message=(
                        "  Что умеет этот бот?\n"
                        "  Здесь мы подбираем пары для Random "
                        "Coffee между студентами "
                        "курса IT-рекрутер и выпускниками "
                        "IT-профессий Практикума.\n"
                        "Если ты новый пользователь, "
                        "бот предложит познакомиться. "
                        "Если у тебя возникли сложности "
                        "в работе или пожелания, "
                        "можешь написать в поддержку"
                    ),
                   message_key="help_message"),
        MessageBot(title="Стартовое сообщение",
                   message=(
                        "Наш бот предлагает тебе поучаствовать "
                        "в неформальном разговоре с "
                        "выпускником Практикума. "
                        'Для этого необходимо нажать на кнопку "Go". '
                        "Если ты не готов на этой неделе участвовать в "
                        'Random Coffee просто нажми "В следующий раз".'
                    ),
                   message_key="start_message"),
        MessageBot(title="Выход",
                   message=(
                        "Будем ждать тебя снова. "
                        "Когда будешь готов, запусти бота командой /start"
                    ),
                   message_key="next_time_message"),
        MessageBot(title="Выбор роли",
                   message="Укажи, пожалуйста, свою роль:",
                   message_key="choose_role_message"),
        MessageBot(title="Поиск пары",
                   message=(
                       "Ищу тебе пару!\nКак только найду, обязательно сообщу!"
                    ),
                   message_key="pair_search_message"),
        MessageBot(title="Выбор действия с именем",
                   message=(
                        'Тебя зовут {}?\nЕсли все верно, нажми "Продолжить"\n'
                        "Если хочешь поправить, пожалуйста, нажми на кнопку "
                        '"Сменить имя"'
                    ),
                   message_key="guess_name_message"),
        MessageBot(title="Ввод имени",
                   message="Напиши свое имя:",
                   message_key="change_name_message"),
        MessageBot(title="Выбор профессии",
                   message="Укажи, пожалуйста, свою профессию:",
                   message_key="choose_profession_message"),
        MessageBot(title="Отсутсвие никнейма, ввод номера",
                   message=(
                        "Не удалось автоматически получить твой никнейм.\n"
                        "Введите, пожалуйста, номер телефона:\n"
                        "Пример ввода: +7(111)111-11-11"
                    ),
                   message_key="username_not_found_message"),
        MessageBot(title="Профиль с никнеймом",
                   message=(
                        "Твой профиль:\n" "Имя: {}\n"
                        "Профессия: {}\n" "Telegram: @{}"
                    ),
                   message_key="profile_message"),
        MessageBot(title="Профиль с номером",
                   message=(
                        "Твой профиль:\n" "Имя: {}\n"
                        "Профессия: {}\n" "Контакты: {}"
                    ),
                   message_key="profile_message_no_username"),
        MessageBot(title="Действия с поиском пары",
                   message="Начать поиск пары?",
                   message_key="start_pair_search_message"),
        MessageBot(title="Вопрос по удачности созвона",
                   message="Удалось ли созвониться? Спасибо :)",
                   message_key="is_pair_successful_message"),
        MessageBot(title="Вывод пары с никнеймом",
                   message=(
                        "Твоя пара на эту неделю:\n"
                        "Имя: {}\n"
                        "Профессия: {}\n"
                        "Telegram: @{}\n"
                        "Напиши своему напарнику приветствие "
                        "и предложи удобные дни и\n"
                        "время для созвона. В разговоре "
                        "ты сможешь опираться на этот гайд\n"
                        "{}"
                    ),
                   message_key="found_pair"),
        MessageBot(title="Вывод пары с номером",
                   message=(
                        "Твоя пара на эту неделю:\n"
                        "Имя: {}\n"
                        "Профессия: {}\n"
                        "Контакты: {}\n"
                        "Напиши своему напарнику приветствие "
                        "и предложи удобные дни и\n"
                        "время для созвона. В разговоре "
                        "ты сможешь опираться на этот гайд\n"
                        "{}"
                    ),
                   message_key="found_pair_no_username"),
        MessageBot(title="После сообщения созвона(студент)",
                   message=(
                        "Спасибо большое за участие. Оставить \n"
                        "обратную связь можно в канале \n"
                        "Communication в твоей когорте. Если тебе\n"
                        "захочется поучаствовать еще раз, просто\n"
                        'нажми кнопку "Go". Если пока не готов\n'
                        'участвовать, нажми кнопку "В следующий раз".'
                    ),
                   message_key="post_call_message_for_student"),
        MessageBot(title="После сообщения созвона(рекрутер)",
                   message=(
                        "Спасибо большое за участие. Оставить \n"
                        "обратную связь можно здесь {}. Если \n"
                        "тебе захочется поучаствовать еще раз, просто\n"
                        'нажми кнопку "Go". Если пока не готов\n'
                        'участвовать, нажми кнопку "В следующий раз".'
                    ),
                   message_key="post_call_message_for_recruiter"),
        MessageBot(title="Исключение из БД пользователя",
                   message=(
                        "Тебя исключили из базы данных как {}, "
                        "теперь ты можешь зарегистрироваться заново."
                    ),
                   message_key="user_delete_message"),
        MessageBot(title="После неудачного созвона",
                   message=(
                        "Нам очень жаль, что у вас не вышло,\n"
                        "пожалуйста, заполни форму {}. \n"
                        "Eсли тебе захочется\n"
                        "поучаствовать еще раз, просто\n"
                        'нажми кнопку "Go". Если пока не готов\n'
                        'участвовать, нажми кнопку "В следующий раз".'
                    ),
                   message_key="post_call_message"),
        MessageBot(title="Некорректный номер, повторный ввод",
                   message="Некорректный номер телефона.\n" "Введите заново:",
                   message_key="message_incorrect_phone_number"),
    )
    MessageBot.objects.bulk_create(messages)


def remove_messages(apps, schema_editor):
    """Удаление сообщений бота."""
    MessageBot = apps.get_model("bot", "MessageBot")
    MessageBot.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0010_messagebot_message_key"),
    ]

    operations = [
        migrations.RunPython(
            create_messages,
            reverse_code=remove_messages
        )
    ]
