# Generated by Django 4.2.7 on 2023-12-02 14:43

from django.db import migrations


def update_messages(apps, schema_editor):
    """Обновление сообщения."""
    MessageBot = apps.get_model("bot", "MessageBot")
    message = (
        MessageBot.objects.get(message_key="post_call_message_for_student")
        )
    message.message_key = "post_call_message_for_it_specialist"
    message.save(update_fields=["message_key"])


def rollingback_update_messages(apps, schema_editor):
    """Откат обновления сообщения."""
    MessageBot = apps.get_model("bot", "MessageBot")
    message = (
        MessageBot.objects.get(
            message_key="post_call_message_for_it_specialist"
            )
        )
    message.message_key = "post_call_message_for_student"
    message.save(update_fields=["message_key"])


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0013_update_messages_in_messagebot"),
    ]

    operations = [
        migrations.RunPython(
            update_messages,
            reverse_code=rollingback_update_messages
        )]
