# Generated by Django 4.2.7 on 2023-11-30 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0012_itspecialist_in_search_pair_recruiter_in_search_pair_and_more"),
        ("bot", "0013_update_messages_in_messagebot"),
    ]

    operations = []
