# Generated by Django 4.2.7 on 2023-12-04 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0014_correct_key_message_post_call_message_for_it_specialist"),
        ("bot", "0014_merge_20231130_0940"),
    ]

    operations = []
