# Generated by Django 4.2.7 on 2023-12-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0015_merge_20231204_1350"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profession",
            options={
                "verbose_name": "Профессия IT специалиста",
                "verbose_name_plural": "Профессии IT специалистов",
            },
        ),
        migrations.AlterField(
            model_name="itspecialist",
            name="last_login_date",
            field=models.DateField(
                auto_now=True, verbose_name="Заходил в последний раз"
            ),
        ),
        migrations.AlterField(
            model_name="itspecialist",
            name="registration_date",
            field=models.DateField(auto_now_add=True, verbose_name="Дата регистрации"),
        ),
        migrations.AlterField(
            model_name="itspecialist",
            name="surname",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="itspecialist",
            name="telegram_username",
            field=models.CharField(
                max_length=255,
                unique=True,
                verbose_name="Ник телеграма или номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="recruiter",
            name="last_login_date",
            field=models.DateField(
                auto_now=True, verbose_name="Заходил в последний раз"
            ),
        ),
        migrations.AlterField(
            model_name="recruiter",
            name="registration_date",
            field=models.DateField(auto_now_add=True, verbose_name="Дата регистрации"),
        ),
        migrations.AlterField(
            model_name="recruiter",
            name="surname",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="recruiter",
            name="telegram_username",
            field=models.CharField(
                max_length=255,
                unique=True,
                verbose_name="Ник телеграма или номер телефона",
            ),
        ),
    ]
