# Generated by Django 4.2.7 on 2023-12-05 01:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0016_alter_profession_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagebot",
            name="message",
            field=ckeditor.fields.RichTextField(
                help_text="Не удаляйте '{}'. Это метка для вставки динамических данных.",
                unique=True,
                verbose_name="Текст сообщения бота",
            ),
        ),
    ]
