# Generated by Django 4.2.7 on 2024-01-12 19:38

from django.db import migrations


def create_parameters(apps, schema_editor):
    """Создание параметров бота."""
    ParameterBot = apps.get_model("bot", "ParameterBot")
    parameters = (
        ParameterBot(
            title="Дней до вопроса о состоявшемся созвоне",
            value=5,
            unit_measurement="дни",
            parameter_key="question_call_day"
        ),
        ParameterBot(
            title=("Дней неактивности пользователя "
                   "для фильтрации удаления через 'Действия'"),
            value=183,
            unit_measurement="дни",
            parameter_key="inactive_users_day"
        ),
    )
    ParameterBot.objects.bulk_create(parameters)


def remove_parameters(apps, schema_editor):
    """Удаление параметров бота."""
    ParameterBot = apps.get_model("bot", "ParameterBot")
    ParameterBot.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0018_parameterbot"),
    ]

    operations = [
        migrations.RunPython(
            create_parameters,
            reverse_code=remove_parameters
        )
    ]
