services:
  redis:
    image: redis:latest
    container_name: redis-coffee-bot
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
      - ../../logs/redis/:/var/log/
    restart: always

  postgres-db:
    image: postgres:13.0-alpine
    container_name: postgres-container-randomcoffee
    env_file:
      - ../../.env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../logs/db/:/var/log/postgres

  bot:
    image: "ghcr.io/studio-yandex-practicum/randomcoffeebottelegram:develop"
    container_name: random-coffee-bot
    restart: always
    volumes:
      - static_value:/app/static/
      - ../../logs/bot/:/app/logs
    env_file:
      - ../../.env
    depends_on:
      - postgres-db
      - redis

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=${HOST_NG}
    volumes:
      - /home/aptalca/appdata/swag:/config
      - ./nginx.stage.conf.template:/etc/nginx/templates/default.conf.template
      - static_value:/var/html/static/
      - ../../logs/nginx/:/var/log/nginx/
    ports:
      - 443:443
      - "80:${PORT_NG}"
    depends_on:
      - bot
    restart: unless-stopped

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:${PORT_NG}"
    volumes:
      - ./nginx.stage.conf.template:/etc/nginx/templates/default.conf.template
      - static_value:/var/html/static/
      - ../../logs/nginx/:/var/log/nginx/
    env_file:
      - ../../.env
    depends_on:
      - bot

volumes:
  redis_data:
  postgres_data:
  static_value:
