services:
  redis:
    image: redis:latest
    container_name: redis-coffee-bot
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: always

  postgres-db:
    image: postgres:13.0-alpine
    container_name: postgres-container-randomcoffee
    env_file:
      - ../../.env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    image: "ghcr.io/studio-yandex-practicum/randomcoffeebottelegram:develop"
    container_name: random-coffee-bot
    restart: always
    volumes:
      - static_value:/app/static/
      - bot_logs:/app/logs/
    env_file:
      - ../../.env
    depends_on:
      - postgres-db
      - redis

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      - bot

volumes:
  redis_data:
  postgres_data:
  static_value:
  bot_logs:
